version: '3'

services:
  db:
    restart: always
    image: postgres
  redis:
    restart: always
    image: redis:latest
  migration:
    build: .
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate'
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "migrate"]
    depends_on:
      - db
      - redis
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
      - redis